export enum Methods {
  P2P_INIT = 'P2P_INIT',
  P2P_DISCONNECT = 'P2P_DISCONNECT',
  P2P_GET_PEERS = 'P2P_GET_PEERS',
  P2P_REMOVE_PEERS = 'P2P_REMOVE_PEERS',
  LEDGER_INIT = 'LEDGER_INIT',
  LOCAL_INIT = 'LOCAL_INIT',
  LOCAL_SAVE_MNEMONIC = 'LOCAL_SAVE_MNEMONIC',
  RESPONSE = 'LOCAL_REQUEST'
}
